### ISSUE TITLE
[minor] Inconsistent output format between enriched_windows and enriched_re

### ISSUE THREAD

**Issue by algaebrown** [YeoLab/skipper#16]
enriched_windows contains only hits with FDR<0.2
enriched_re outputs everything (including FDR>0.2)

**Comment by evanb-exai** [comment]
Yes this is intentional because there aren't so many REs, and thresholding may depend heavily on the use case. In the paper I added a fold change cutoff beyond the FDR, which was not done for the genomic windows.
