### ISSUE TITLE
Some misleading in Skipper_config.py

### ISSUE THREAD

**Issue by Lindky** [YeoLab/skipper#27]
I'm looking for clarification on the Skipper config file. Some terms really confused me. 

Does the "STAR_DIR" refer to the STAR index folder?  

Could you provide an example for the "REPEAT_TABLE"? I downloaded the coordinates of the repetitive element from the whole genome from the USCD genome browser with the repeatMasker format. However, I got an error that says the output file for the REPEAT_bed is missing. I'm wondering whether the format of my REPEAT_TABLE is correct.

**Comment by byee4** [comment]
> Does the "STAR_DIR" refer to the STAR index folder?


Yes that's correct

> Could you provide an example for the "REPEAT_TABLE"? I downloaded the coordinates of the repetitive element from the whole genome from the USCD genome browser with the repeatMasker format. However, I got an error that says the output file for the REPEAT_bed is missing. I'm wondering whether the format of my REPEAT_TABLE is correct.


Here is an example of a repeat table:
https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz

The REPEAT_BED param should be a valid path but does not need to exist, as the pipeline will attempt to create this file from REPEAT_TABLE:
https://github.com/YeoLab/skipper/blob/55bf887551af44a50f316cd39db48d330876cca7/Skipper.py#L383

**Comment by Lindky** [comment]
Thanks! It can now successfully run on my samples.
