### ISSUE TITLE
information about intergenic enriched windows

### ISSUE THREAD

**Issue by VandaLovejoy** [YeoLab/skipper#31]
Hi! Thank you so much for this great tool. I'd like to know how it is possible to get information about enriched intergenic regions using Skipper. 
Thanks!
Vanda

**Comment by augustboyle** [comment]
Hello Vanda,I have not created a list including intergenic reasons but it is possible to supply your own regions. You could add intergenic windows to the PARTITION and FEATURE_ANNOTATIONS output or you could add intergenic annotations to the GFF input and run the commands to create the windows. Either way you would need to specify a new feature type and include it in the ACCESSION_RANKINGS input.If you know there is a lot of binding in intergenic regions and not so much in known transcripts then another option would be to run a GFF of those alone. This would be a natural use case to support but some gene based features would have to be reworked so it hasn’t happened yet!Courtesy of my phoneOn Aug 12, 2024, at 11:55 AM, VandaLovejoy ***@***.***> wrote:﻿
Hi! Thank you so much for this great tool. I'd like to know how it is possible to get information about enriched intergenic regions using Skipper.
Thanks!
Vanda

**Comment by VandaLovejoy** [comment]
thank you!!!

________________________________
De : Evan Boyle ***@***.***>
Envoyé : lundi 12 août 2024 17:01
À : YeoLab/skipper ***@***.***>
Cc : Vanda Gaonac'h-Lovejoy ***@***.***>; Author ***@***.***>
Objet : Re: [YeoLab/skipper] information about intergenic enriched windows (Issue #31)


Hello Vanda,I have not created a list including intergenic reasons but it is possible to supply your own regions. You could add intergenic windows to the PARTITION and FEATURE_ANNOTATIONS output or you could add intergenic annotations to the GFF input and run the commands to create the windows. Either way you would need to specify a new feature type and include it in the ACCESSION_RANKINGS input.If you know there is a lot of binding in intergenic regions and not so much in known transcripts then another option would be to run a GFF of those alone. This would be a natural use case to support but some gene based features would have to be reworked so it hasn’t happened yet!Courtesy of my phoneOn Aug 12, 2024, at 11:55 AM, VandaLovejoy ***@***.***> wrote:﻿
Hi! Thank you so much for this great tool. I'd like to know how it is possible to get information about enriched intergenic regions using Skipper.
Thanks!
Vanda
