### ISSUE TITLE
How do I modify skipper_config.py to re-run snakmake with the bam generated earlier in your script

### ISSUE THREAD

**Issue by zhenyu7500** [YeoLab/skipper#33]
Hi, skipper developer,

Thank you for developing such a great tool! 
Because of some R-dependent errors, after skipper snakemake generated bam, the pipeline was interrupted.
I solved the corresponding problem later.

I want to use this bam as input to rerun skipper, how should I modify the skipper_config.py file？

Thanks for your kindly help！

**Comment by augustboyle** [comment]
Hello,

If the Snakemake generated the BAMs using the skipper_config.py file you should not have to change the config file at all. Snakemake might be confused by file timestamps if you updated something; in this case, you could explore options for snakemake to ignore timestamps, specifically the -t option to touch all the BAMs in order.

Alternatively, you can make a new directory and provide a manifest with BAM files using the "Input_bam" and "CLIP_bam" fields. This should run from the BAMs directly but might be slightly confusing to track all the steps that were run.
