### ISSUE TITLE
 Handling Consecutive Enriched Windows as Merged Peaks

### ISSUE THREAD

**Issue by VandaLovejoy** [YeoLab/skipper#39]
Hello,

Thank you for creating such an excellent tool! I've successfully generated a list of enriched windows, but I noticed that some windows are consecutive and could potentially be merged into a single peak. While I understand that the tool uses fixed window lengths, I was wondering if there's a way to merge these consecutive peaks while retaining statistical information for them.

I could use tools like bedtools to merge the peaks, but I am unsure how to handle the counts and enrichment data in such cases. Could you provide guidance or suggest best practices for dealing with consecutive peaks in a way that preserves meaningful statistical information?

Thank you for your help!

Best regards, 
Vanda

**Comment by augustboyle** [comment]
Hello,

It sounds like you would like to use the finemapping output. This merges adjacent windows and picks non-overlapping 75-nt windows with local maxima of signal. This was used for modeling sequence specificity in the paper.
