### ISSUE TITLE
Questions about the peak output columns in reproducible_enriched_windows directory

### ISSUE THREAD

**Issue by zhenyu7500** [YeoLab/skipper#40]
Dear Skipper developers,

Thank you for creating skipper, such a powerful and user-friendly tool for calling peaks in CLIP-seq data. While using Skipper, I noticed that it can sometimes be overly sensitive, as many peaks in the track plot do not appear to have substantial read support. Therefore, I would like to filter out some of these peaks.
Could you please clarify the meaning of the following columns in the output files from the reproducible_enriched_windows directory?
enrichment_n
enrichment_l2or_min
enrichment_l2or_mean
enrichment_l2or_max
p_max
p_min
q_max
q_min

If I want to filter out peaks with insufficient read support, which column(s) and cutoff value(s) would you recommend? In a previous issue (https://github.com/YeoLab/skipper/issues/18), it was suggested to use peaks with an enrichment value greater than 3.3 or q-value less than e-3. However, I am uncertain which column in the output corresponds to this recommendation.
Thank you in advance for your guidance!

Best regards,

Zhenyu

**Comment by augustboyle** [comment]
Hello,

enrichment_n: number of replicates aggregated
enrichment_l2or_min: minimum replicate log2 odds ratio
enrichment_l2or_mean: mean replicate log2 odds ratio
enrichment_l2or_max: maximum replicate log2 odds ratio
p_max: maximum replicate betabinomial p-value
p_min: minimum replicate betabinomial p-value
q_max: maximum replicate betabinomial q-value
q_min: minimum replicate betabinomial q-value

If you want a minimum number of supporting reads, you can use the clip_sum column or combine the clip_sum with the input_sum column. The strength of the binding is best captured by the enrichment log2 odds ratio. If your replicates are similarly powered, I would use the mean. How stringent you filter really depends on your application and why you wish to filter to stronger hits.

**Comment by zhenyu7500** [comment]
Hello,

thank you for your kindly response！
