### ISSUE TITLE
finemapped_windows from the manuscript

### ISSUE THREAD

**Issue by CharlotteAnne** [YeoLab/skipper#7]
Hi!
I was wondering if you could please let me know what are the meanings of the columns in the finemapped_windows provided with the Skipper manuscript? ie. what are the last three columns here:
chr1	109591499	109591574	MW:1:1	0	-	2	86	1
Thank you!

**Comment by CharlotteAnne** [comment]
Also - is it possible to produce the fine-mapped windows from the code here?

**Comment by augustboyle** [comment]
Hi Charlotte,The three fields are input reads in the window, CLIP reads in the window, and the scaled rank of the finemapped window per the contiguous merged windows called by Skipper (the one with the most signal is 1 and subsequent windows are interspersed from 0). Finemapped window output is included by default when running Skipper and you could modify the finemap_enriched_windows script to alter the heuristic.EvanCourtesy of my phoneOn Jun 7, 2023, at 8:30 AM, Charlotte Capitanchik ***@***.***> wrote:﻿
Also - is it possible to produce the fine-mapped windows from the code here?

**Comment by CharlotteAnne** [comment]
Super helpful - thank you!!
