### ISSUE TITLE
Execution haulted due to error in rule fit_input_betabinomial_re_model

### ISSUE THREAD

**Issue by ajritter8** [YeoLab/skipper#9]
Below is what was printed under Error in rule fit_input_betabinomial_re_model:
> Delimiter: "\t"
> dbl (6): repeat_name, KO_IN_1, KO_IN_2, KO_IN_3, KO_IP_1, KO_IP_2
> lgl (1): KO_IP_3
> 
> ℹ Use `spec()` to retrieve the full column specification for this data.
> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> Warning message:
> One or more parsing issues, call `problems()` on your data frame for details, e.g.:
>   dat <- vroom(...)
>   problems(dat) 
> Error in vglm.fitter(x = x, y = y, w = w, offset = offset, Xm2 = Xm2,  : 
>   object 'eta' not found
> Calls: %>% ... <Anonymous> -> vglm.fitter -> <Anonymous> -> eta2theta
> In addition: Warning messages:
> 1: In min(y) : no non-missing arguments to min; returning Inf
> 2: In max(abs(ycounts - round(ycounts))) :
>   no non-missing arguments to max; returning -Inf
> Execution halted

Another error I'm getting in the same step for other samples is:
> Error in `group_by()`:
> ℹ In argument: `gc_bin = cut_number(gc, 10)`.
> Caused by error in `cut_number()`:
> ! Insufficient data values to produce 10 bins.
> Backtrace:
>      ▆
>   1. ├─... %>% group_by(gc_bin = cut_number(gc, 10))
>   2. ├─dplyr::group_by(., gc_bin = cut_number(gc, 10))
>   3. ├─dplyr:::group_by.data.frame(., gc_bin = cut_number(gc, 10))
>   4. │ └─dplyr::group_by_prepare(.data, ..., .add = .add, error_call = current_env())
>   5. │   └─dplyr:::add_computed_columns(.data, new_groups, error_call = error_call)
>   6. │     └─dplyr:::mutate_cols(...)
>   7. │       ├─base::withCallingHandlers(...)
>   8. │       └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
>   9. │         └─mask$eval_all_mutate(quo)
>  10. │           └─dplyr (local) eval()
>  11. └─ggplot2::cut_number(gc, 10)
>  12.   └─cli::cli_abort("Insufficient data values to produce {n} bins.")
>  13.     └─rlang::abort(...)
> Execution halted

Any suggestions for what to check in either the input files or workarounds in the Rscript itself?

**Comment by augustboyle** [comment]
Hello,

Can you examine the repeat count tables (output/counts/repeats/tables/name/{experiment_label}.tsv.gz)? You can send me a few rows of the output

The error suggests that the counts might be missing or identical across replicates or all zeros.

Best,
Evan

**Comment by ajritter8** [comment]
Hey Evan,

Thanks for the reply and sorry for the delayed response.  I double-checked
the outputs and found that at the trimming and UMI-removal steps, the
resulting FASTQs were empty.  So all following steps failed to produce
outputs.  I tested running Skewer on one of my input FASTQs and it failed
because of a *Malformed fastq record error*.  To give some context, the
data I'm working with is RBP-eCLIP data from Eclipse Bioinnovations.  They
sent me raw and adapter-trimmed + UMI-removed FASTQs, and what I'm
inputting into Skipper are the raw FASTQs.  Before trying Skipper, I did
map the further processed FASTQs using STAR and I have the BAMs.  I
initially wanted to run Skipper on the BAMs (skipping all steps related to
FASTQ QC, processing and mapping) but I have not been able to find clear
instructions on how to do so.  Would you be able to direct me to a more
detailed instruction manual or let me know how to start from BAMs?

Best,

Alex

**Comment by ajritter8** [comment]
Hey Evan,

Thanks for that.  Unfortunately partition_bam_reads and quantify_repeats
are both failing due to *"ERROR: chrom "GL000008.2" not found in genome
file. Exiting."* although the reads were mapped to a STAR index made from
GRCh38 and gencode.v38.primary_assemby.gtf 🤔 which I checked contains that
chromosome.

- Alex

**Comment by ajritter8** [comment]
Hey Evan,

Update: I was able to get Skipper to run successfully on my 3 data sets.  I
was a bit surprised however, at the number of reproducible enriched windows
that were identified...  For context, in one cell line, we did an
RBP-eCLIP, Ago2-eCLIP, and Ago2-eCLIP in the RBP-KO version of that cell
line (all in triplicate).  Skipper identified 128592, 0 and 249
reproducible enriched windows in those samples respectively... The first
number seems too high and the other two seem unexpectedly low.  Any
suggestions for how and at which step(s) I can adjust the stringency to
either reduce or increase the number of windows called?

Thanks,

Alex

**Comment by augustboyle** [comment]
Hi Alex,I would check the enriched windows from the individual replicates to assess how much variability you have per replicate. Perhaps some of the replicates have many more hits than others which you could follow up on. More broadly the threshold is already quite permissive (20% FDR). You can find non-significant enriched windows and look at the number of informative reads using the count tables however. Perhaps there were not very many reads in some of the conditions/replicates?EvanCourtesy of my phoneOn Jul 18, 2023, at 3:08 PM, Alexander J Ritter ***@***.***> wrote:﻿
Hey Evan,



Update: I was able to get Skipper to run successfully on my 3 data sets.  I

was a bit surprised however, at the number of reproducible enriched windows

that were identified...  For context, in one cell line, we did an

RBP-eCLIP, Ago2-eCLIP, and Ago2-eCLIP in the RBP-KO version of that cell

line (all in triplicate).  Skipper identified 128592, 0 and 249

reproducible enriched windows in those samples respectively... The first

number seems too high and the other two seem unexpectedly low.  Any

suggestions for how and at which step(s) I can adjust the stringency to

either reduce or increase the number of windows called?



Thanks,



Alex



On Wed, Jul 12, 2023 at 2:20 PM Alexander Ritter ***@***.***>

wrote:

**Comment by ajritter8** [comment]
Okay great, so I can see exactly where to adjust the FDR in
call_enriched_windows.R, but where can I adjust the code to deal with
potentially smaller counts (the Ago2-eCLIP samples had 8-15 million reads
for example)?

**Comment by augustboyle** [comment]
Could you say more about what you are interested in trying?The statistical framework directly computes the p value from the overdispersion and counts. You can change which windows are tested and inspect different ranges of odds ratio or p value but I can’t think of any other way to tune the testing. Also the framework assumes that most windows are not enriched so pruning the windows with independent filtration might make the calling less sensitive.Courtesy of my phoneOn Jul 19, 2023, at 3:46 PM, Alexander J Ritter ***@***.***> wrote:﻿
Okay great, so I can see exactly where to adjust the FDR in

call_enriched_windows.R, but where can I adjust the code to deal with

potentially smaller counts (the Ago2-eCLIP samples had 8-15 million reads

for example)?

**Comment by ajritter8** [comment]
Hey Evan,

   - Right, so for the problem of having too many RBP-eCLIP reproducible
   windows, I'm planning to make the FDR filter 5%.  Could I just alter line
   207 in call_enriched_windows.R to the line below?:

enriched_window_data = q_data %>% filter(above_threshold, qvalue <= 0.05)
> %>% select(-above_threshold) %>% left_join(feature_annotations) %>%
> arrange(qvalue)
>


   - For the problem of having very little to no reproducible windows in
   the two Ago2 datasets, I want to see about increasing the sensitivity of
   reproducible window detection.  To my understanding, the log2 fold change
   cutoff for enriched windows is >=2.5.  I want to try reducing that to 2.0.
   Would you be able to direct me to which line(s) of code in
   call_enriched_windows.R to change to do that?

I really appreciate your help,

Alex

**Comment by augustboyle** [comment]
Hi Alex,

You could change the FDR cutoff in that case but I would recommend taking the top 10,000 windows or filtering to a desired level as measured by enrichment instead. If a window passes a 20% FDR in each of two replicates that is likely stringent enough and the enrichment odds ratio is probably a better measure of signal.

For the enriched windows, there is no enrichment cutoff for reporting results. The only filtering in the code or the paper is on repetitive element output for the RBP clustering results because I found that having lots of non-significant simple repeats added noise to the clustering. That analysis is not part of the Skipper workflow per se - the results of the clustering are provided as an annotation file.

The only suggestions I have for reviewing non-significant windows are to look at the most enriched windows in the count tables and browse the BAMs on IGV at these sites to see whether whether they may be meaningful or if something might be wrong with the data.

Best,

Evan

**Comment by ajritter8** [comment]
Great, I think I’m all set now.  Thanks so much for all your help!
